#pragma config(Sensor, in2,    line2,          sensorLineFollower)
#pragma config(Sensor, in3,    line3,          sensorLineFollower)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Motor,  port2,           mot1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mot2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mot3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mot4,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lastImput;
int curImput;
bool toggle;



void tankDrive(int leftSpeed, int rightSpeed) {
	/*
	_|_
	mot 1|-|   |-|mot 3
	|   |
	mot 2|-|___|-|mot 4
	*/
	motor[mot1] = leftSpeed;
	motor[mot2] = -1 * leftSpeed;
	motor[mot3] = -1 * rightSpeed;
	motor[mot4] = rightSpeed;
}
task main()
{
	while(true){
		curImput = SensorValue[button1];
		if(curImput == 1 && lastImput != curImput){
			toggle = !toggle;
		}
		if(toggle){

			if(SensorValue[line2] > 2000){
			tankDrive(35,-35);
			}
			else if(SensorValue[line3] > 2000){
			tankDrive(-35,35);
			}
			else{
			tankDrive(35,35);
			}


			// tankDrive(35,35);
		}
		else{
			tankDrive(0 ,0);
		}
		wait1Msec(10);
		lastImput = curImput;
	}
}
